<?php

namespace App\Enums;

enum ShipType: string
{

    case COMMAND_FRIGATE = 'SHIP_COMMAND_FRIGATE';
    case EXPLORER = 'SHIP_EXPLORER';
    case HEAVY_FREIGHTER = 'SHIP_HEAVY_FREIGHTER';
    case INTERCEPTOR = 'SHIP_INTERCEPTOR';
    case LIGHT_HAULER = 'SHIP_LIGHT_HAULER';
    case LIGHT_SHUTTLE = 'SHIP_LIGHT_SHUTTLE';
    case MINING_DRONE = 'SHIP_MINING_DRONE';
    case ORE_HOUND = 'SHIP_ORE_HOUND';
    case PROBE = 'SHIP_PROBE';
    case REFINING_FREIGHTER = 'SHIP_REFINING_FREIGHTER';
    case SIPHON_DRONE = 'SHIP_SIPHON_DRONE';
    case SURVEYOR = 'SHIP_SURVEYOR';

}
