<?php

namespace App\Enums;

enum WaypointTraitSymbol: string
{

    case ASH_CLOUDS = 'ASH_CLOUDS';
    case BARREN = 'BARREN';
    case BLACK_MARKET = 'BLACK_MARKET';
    case BREATHABLE_ATMOSPHERE = 'BREATHABLE_ATMOSPHERE';
    case BUREAUCRATIC = 'BUREAUCRATIC';
    case CANYONS = 'CANYONS';
    case COMMON_METAL_DEPOSITS = 'COMMON_METAL_DEPOSITS';
    case CORROSIVE_ATMOSPHERE = 'CORROSIVE_ATMOSPHERE';
    case CORRUPT = 'CORRUPT';
    case CRUSHING_GRAVITY = 'CRUSHING_GRAVITY';
    case DEBRIS_CLUSTER = 'DEBRIS_CLUSTER';
    case DEEP_CRATERS = 'DEEP_CRATERS';
    case DIVERSE_LIFE = 'DIVERSE_LIFE';
    case DRY_SEABEDS = 'DRY_SEABEDS';
    case EXPLORATION_OUTPOST = 'EXPLORATION_OUTPOST';
    case EXPLOSIVE_GASES = 'EXPLOSIVE_GASES';
    case EXTREME_PRESSURE = 'EXTREME_PRESSURE';
    case EXTREME_TEMPERATURES = 'EXTREME_TEMPERATURES';
    case FOSSILS = 'FOSSILS';
    case FROZEN = 'FROZEN';
    case HIGH_TECH = 'HIGH_TECH';
    case HOLLOWED_INTERIOR = 'HOLLOWED_INTERIOR';
    case ICE_CRYSTALS = 'ICE_CRYSTALS';
    case INDUSTRIAL = 'INDUSTRIAL';
    case JOVIAN = 'JOVIAN';
    case JUNGLE = 'JUNGLE';
    case MAGMA_SEAS = 'MAGMA_SEAS';
    case MARKETPLACE = 'MARKETPLACE';
    case MEGA_STRUCTURES = 'MEGA_STRUCTURES';
    case METHANE_POOLS = 'METHANE_POOLS';
    case MICRO_GRAVITY_ANOMALIES = 'MICRO_GRAVITY_ANOMALIES';
    case MILITARY_BASE = 'MILITARY_BASE';
    case MINERAL_DEPOSITS = 'MINERAL_DEPOSITS';
    case MUTATED_FLORA = 'MUTATED_FLORA';
    case OCEAN = 'OCEAN';
    case OUTPOST = 'OUTPOST';
    case OVERCROWDED = 'OVERCROWDED';
    case PERPETUAL_DAYLIGHT = 'PERPETUAL_DAYLIGHT';
    case PERPETUAL_OVERCAST = 'PERPETUAL_OVERCAST';
    case PIRATE_BASE = 'PIRATE_BASE';
    case PRECIOUS_METAL_DEPOSITS = 'PRECIOUS_METAL_DEPOSITS';
    case RADIOACTIVE = 'RADIOACTIVE';
    case RARE_METAL_DEPOSITS = 'RARE_METAL_DEPOSITS';
    case RESEARCH_FACILITY = 'RESEARCH_FACILITY';
    case ROCKY = 'ROCKY';
    case SALT_FLATS = 'SALT_FLATS';
    case SCARCE_LIFE = 'SCARCE_LIFE';
    case SCATTERED_SETTLEMENTS = 'SCATTERED_SETTLEMENTS';
    case SHALLOW_CRATERS = 'SHALLOW_CRATERS';
    case SHIPYARD = 'SHIPYARD';
    case SPRAWLING_CITIES = 'SPRAWLING_CITIES';
    case STRIPPED = 'STRIPPED';
    case STRONG_GRAVITY = 'STRONG_GRAVITY';
    case STRONG_MAGNETOSPHERE = 'STRONG_MAGNETOSPHERE';
    case SUPERVOLCANOES = 'SUPERVOLCANOES';
    case SURVEILLANCE_OUTPOST = 'SURVEILLANCE_OUTPOST';
    case SWAMP = 'SWAMP';
    case TEMPERATE = 'TEMPERATE';
    case TERRAFORMED = 'TERRAFORMED';
    case THIN_ATMOSPHERE = 'THIN_ATMOSPHERE';
    case TOXIC_ATMOSPHERE = 'TOXIC_ATMOSPHERE';
    case TRADING_HUB = 'TRADING_HUB';
    case UNCHARTED = 'UNCHARTED';
    case UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION';
    case UNSTABLE_COMPOSITION = 'UNSTABLE_COMPOSITION';
    case VAST_RUINS = 'VAST_RUINS';
    case VIBRANT_AURORAS = 'VIBRANT_AURORAS';
    case VOLCANIC = 'VOLCANIC';
    case WEAK_GRAVITY = 'WEAK_GRAVITY';

}
